name: firebase_auth_demo
description: Demonstraiting flutter auth bug
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.0-134.1.beta <3.0.0"

dependencies:
  firebase_auth: ^3.3.4
  firebase_core: ^1.10.6
  uni_links: ^0.5.1

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
